
# Required for including libtorrent headers
LIBTORRENT_LOCATION = C:/libtorrent-rasterbar-1.0.2
INCLUDEPATH += $$LIBTORRENT_LOCATION/include

DEFINES += WIN32
DEFINES += BOOST_ASIO_SEPARATE_COMPILATION
DEFINES += TORRENT_DISABLE_GEO_IP
DEFINES += TORRENT_NO_DEPRECATE

# Required for including boost headers
BOOST_LOCATION = C:/boost_1_56_0
INCLUDEPATH += $$BOOST_LOCATION











