#!/bin/bash
spec=`qmake -query QMAKE_XSPEC`

if [ "$spec" != "macx-clang" ]
then
  echo "osx build environment not correctly setup"
  exit 1
fi

git submodule init --recursive
git submodule update --recursive

echo "Building All Joystream dependencies..."
pushd deps/osx/
if BUILD_TYPE="DEBUG" ./build-all.sh
then
   echo "Done Building Dependencies"
else
   echo "Building Dependencies failed"
   exit 1
fi
popd

pushd bitcoin/src/detail/store
make
popd

mkdir -p build/osx
cd build/osx
rm -fr app/app.app
qmake ../../JoyStream.pro -r -spec macx-clang CONFIG+=x86_64 CONFIG+=debug && \
  make && \
  macdeployqt app/app.app
