#!/bin/bash
pushd deps/linux
./build-all.sh
popd

mkdir -p build/linux-x64
cd build/linux-x64
make clean
qmake ../../JoyStream.pro -r -spec linux-g++  DEFINES+=QT_FORCE_ASSERTS && make

#sudo cp app/app /media/sf_vm-shared/core.bin
