#!/bin/bash

spec=`qmake -query QMAKE_XSPEC`

if [ "$spec" != "linux-g++" ]
then
  echo "linux build environment not setup correctly"
  exit 1
fi

git submodule update --init --recursive

pushd deps/linux
if BUILD_TYPE="DEBUG" ./build-all.sh
then
   echo "Done Building Dependencies"
else
   echo "Building Dependencies failed"
   exit 1
fi
popd

pushd bitcoin/src/detail/store
make
popd

mkdir -p build/linux-x64
cd build/linux-x64
qmake ../../JoyStream.pro -r -spec linux-g++  CONFIG+=debug && make

#sudo cp app/app /media/sf_vm-shared/core.bin
