#!/bin/bash

spec=`qmake -query QMAKE_XSPEC`

if [ "$spec" != "linux-g++" ]
then
  echo "linux build environment not setup correctly"
fi

pushd bitcoin/src/detail/store
make clean
make
popd

pushd deps/linux
BUILD_TYPE="DEBUG" ./build-all.sh
popd

mkdir -p build/linux-x64
cd build/linux-x64
make clean
qmake ../../JoyStream.pro -r -spec linux-g++  CONFIG+=debug && make

#sudo cp app/app /media/sf_vm-shared/core.bin
