#ifndef BITCOIN_REGTEST_FRAMEWORK_GLOBAL_HPP
#define BITCOIN_REGTEST_FRAMEWORK_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(BITCOIN_REGTEST_FRAMEWORK_LIBRARY)
#  define BITCOIN_REGTEST_FRAMEWORKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BITCOIN_REGTEST_FRAMEWORKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BITCOIN_REGTEST_FRAMEWORK_GLOBAL_HPP
