#ifndef ALERT_TYPES_HPP
#define ALERT_TYPES_HPP

#include <libtorrent/alert_types.hpp>

#define PLUGIN_STATUS_ALERT_ID (libtorrent::user_alert_id + 1)
#define TORRENT_PLUGIN_STATUS_ALERT_ID (PLUGIN_STATUS_ALERT_ID + 1)
#define BUYER_TORRENT_PLUGIN_STATUS_ALERT_ID (TORRENT_PLUGIN_STATUS_ALERT_ID + 1)
#define SELLER_TORRENT_PLUGIN_STATUS_ALERT_ID (BUYER_TORRENT_PLUGIN_STATUS_ALERT_ID + 1)

#endif // ALERT_TYPES_HPP
